### ISSUE TITLE
exception thrown on first and every refresh() when using 1.54" monochrome EPaper display

### ISSUE THREAD

**Issue by caileighf** [adafruit/Adafruit_CircuitPython_SSD1681#9]
Looks like Adafruit started shipping the 1.54" monochrome display with the SSD1681 chipset as of June 7th 2021. https://www.adafruit.com/product/4196

For some reason I can get an initial image on the display but cannot refresh without throwing an exception ("refreshed too soon!"). Is anyone else having issues with this? I can post code but I imagine I'm not the only one having this issue. I have tested with the STM32 feather and the Feather M4 with the same results. I've tried using the busy pin and not with the same results. I've been following the tutorials for CircuitPython but was only able to get the display to refresh by using a different micropython driver..

**Comment by makermelissa** [comment]
@caileighf what does your code look like that you are running? By default, you can't refresh more than once every 180 seconds. You may want to try running simpletest if your code isn't working. I just verified the sample code (and this library) are working fine with the latest release of CircuitPython.

**Comment by makermelissa** [comment]
Whoops, just noticed you posted about the monochrome display and I tested the tri-color.

**Comment by caileighf** [comment]
Hi @makermelissa I actually just came to the same conclusion as you and found your issue (https://github.com/adafruit/circuitpython/issues/2137) really helpful! I got the code working when I used these lines:
```
display.show(None)
display.show(splash)
display.refresh()
```
I also needed to add a shorter `seconds_per_frame` value to the `adafruit_ssd1681.SSD1681` constructor. 

I'm using the Adafruit Feather M4 (https://www.adafruit.com/product/3857) and the 1.54" Monochrome EPaperDisplay (https://www.adafruit.com/product/4196) with the Adafruit SSD1681 `displayio` driver. The Feather is running CircuitPython 7.0.0. 

Currently I'm able to refresh and not have issues with the `displayio` objects showing up offset from their original position (I can't find that issue but I think you were on that thread? I'll keep looking and post here if I find it. It was for an older version of CircuitPython 5.0.0 I think? Essentially, after updating an instance of type `label.Label`s `.text` attribute, it would show up on the display offset vertically from the original location and the x, y position for the object hadn't changed). I think `display.show(None)` was needed before each `display.show(splash)` and subsequent `display.refresh()` following your init/deinit logic in the issue. 

The inability to `refresh()` issue is solved by passing a `seconds_per_frame` value to the `adafruit_ssd1681.SSD1681` constructor BUT, the additional `display.show(None)` and subsequent `display.show(splash)` solve a different issue (offsetting issue which _always_ occurred for me even when `refresh()` was working).

**Comment by caileighf** [comment]
I apologize for the delay! I need to post my code. I'll get to that ASAP. Need to cut it down to a minimal example.

**Comment by makermelissa** [comment]
It turns out I didn't have the correct display on hand to test anyhow, so it should be here in a couple days. My monochrome ones were both older ones. Although it shouldn't normally need that code to work, it might in its current state because I probably never updated the driver to work with the monochrome display since I didn't have one.

**Comment by caileighf** [comment]
I really appreciate it @makermelissa ! Thanks!
